Repository flameshot-org/flameshot, pull requests merged in 2025-05, with the labels that each got.

#3663 Use QStandardPaths::ApplicationsLocation (XDG_*) for open with
  src/tools/launcher/applauncherwidget.cpp
Labels: Linux

#3950 Move ARM CI to a new CI
  .github/workflows/Linux-arm-pack.yml
  .github/workflows/Linux-pack.yml
Labels: CI

#3699 Adds Support for Command-Line on Windows
  README.md
  src/CMakeLists.txt
  src/main.cpp
  src/windows-cli.cpp
Labels: CLI, Windows
